import { Montserrat } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav/Nav";

const inter = Montserrat({
  subsets: ["latin"],
  weight: ["200", "300", "500", "600"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
